/**
 * Mock-данные — заменяются ответами API при подключении БД
 * Омский автотранспортный колледж (ОАТК)
 */

const MOCK_DATA = {
  /** Личные коды доступа — в БД: таблица access_codes */
  accessCodes: {
    '123-123-123': 1,       // Яша Кузнецов (студент)
    '456-456-456': 6,       // Ольга Сидорова (преподаватель)
  },

  groups: ['исп341', 'исп342', 'исп343', 'ат231', 'ат232', 'э1031', 'э1032', 'тм241', 'др351'],
  directions: [
    'Информационные системы и программирование',
    'Автомобили и автомобильное хозяйство',
    'Экономика и бухгалтерский учёт',
    'Технология транспортных процессов',
    'Дорожное строительство и эксплуатация автомобильных дорог',
  ],

  users: [
    {
      id: 1,
      name: 'Яша Кузнецов',
      email: 'kuznetsov@oatk.ru',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Yasha',
      group: 'исп341',
      direction: 'Информационные системы и программирование',
      course: 1,
      interests: ['Python', 'Веб-разработка', 'Игры'],
      online: true,
      role: 'student',
      bio: 'Первокурсник группы исп341. Учусь на информационные системы и программирование.',
    },
    {
      id: 2,
      name: 'Мария Козлова',
      email: 'kozlova@oatk.ru',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
      group: 'исп341',
      direction: 'Информационные системы и программирование',
      course: 1,
      interests: ['UI/UX', 'Figma', 'Фотография'],
      online: true,
      role: 'student',
      bio: 'Одногруппница из исп341.',
    },
    {
      id: 3,
      name: 'Дмитрий Волков',
      email: 'volkov@oatk.ru',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Dmitry',
      group: 'ат231',
      direction: 'Автомобили и автомобильное хозяйство',
      course: 2,
      interests: ['Двигатели', 'Ремонт', 'Футбол'],
      online: false,
      role: 'student',
      bio: 'Студент группы ат231.',
    },
    {
      id: 4,
      name: 'Елена Новикова',
      email: 'novikova@oatk.ru',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Elena',
      group: 'э1031',
      direction: 'Экономика и бухгалтерский учёт',
      course: 2,
      interests: ['Бухучёт', '1С', 'Танцы'],
      online: true,
      role: 'student',
      bio: 'Студентка группы э1031.',
    },
    {
      id: 5,
      name: 'Игорь Петров',
      email: 'petrov@oatk.ru',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Igor',
      group: 'тм241',
      direction: 'Технология транспортных процессов',
      course: 3,
      interests: ['Логистика', 'Стартапы', 'Шахматы'],
      online: false,
      role: 'student',
      bio: 'Студент 3 курса, группа тм241.',
    },
    {
      id: 6,
      name: 'Ольга Сидорова',
      email: 'sidorova@oatk.ru',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Olga',
      group: '—',
      direction: 'Информационные системы и программирование',
      course: 0,
      interests: [],
      online: true,
      role: 'teacher',
      bio: 'Преподаватель программирования. Куратор группы исп341.',
    },
  ],

  chatTypes: {
    channel: { label: 'Канал', readonly: true },
    group: { label: 'Группа', readonly: false },
    direction: { label: 'Направление', readonly: false },
    course: { label: 'Курс', readonly: false },
    flood: { label: 'Флудилка', readonly: false },
    dm: { label: 'ЛС', readonly: false },
  },

  chats: [
    {
      id: 1,
      name: 'Объявления ОАТК',
      type: 'channel',
      avatar: null,
      icon: '📢',
      members: 980,
      description: 'Официальные объявления колледжа. Писать могут только преподаватели и администрация.',
      unread: 2,
      lastMessage: 'Расписание занятий на следующую неделю опубликовано',
      lastTime: '10:30',
    },
    {
      id: 2,
      name: 'исп341',
      type: 'group',
      avatar: null,
      icon: '👥',
      members: 25,
      description: 'Чат группы исп341. Пары, дедлайны, совместные проекты.',
      unread: 3,
      lastMessage: 'Мария: Кто сделал лабу по HTML?',
      lastTime: '11:42',
    },
    {
      id: 3,
      name: 'ИСиП — направление',
      type: 'direction',
      avatar: null,
      icon: '🎓',
      members: 124,
      description: 'Общий чат направления «Информационные системы и программирование».',
      unread: 0,
      lastMessage: 'Преподаватель: Материалы к занятию выложены',
      lastTime: '09:15',
    },
    {
      id: 4,
      name: '1 курс',
      type: 'course',
      avatar: null,
      icon: '📚',
      members: 280,
      description: 'Чат всех студентов 1 курса ОАТК.',
      unread: 1,
      lastMessage: 'Елена: Завтра экскурсия на базу!',
      lastTime: '08:00',
    },
    {
      id: 5,
      name: 'Флудилка ОАТК',
      type: 'flood',
      avatar: null,
      icon: '💬',
      members: 650,
      description: 'Свободное общение на любые темы.',
      unread: 7,
      lastMessage: 'Игорь: Кто смотрел матч вчера?',
      lastTime: '12:01',
    },
    {
      id: 6,
      name: 'Мария Козлова',
      type: 'dm',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
      icon: null,
      members: 2,
      description: 'Личная переписка',
      unread: 1,
      lastMessage: 'Скинешь домашку по CSS?',
      lastTime: '11:55',
      userId: 2,
    },
    {
      id: 7,
      name: 'Дмитрий Волков',
      type: 'dm',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Dmitry',
      icon: null,
      members: 2,
      description: 'Личная переписка',
      unread: 0,
      lastMessage: 'Спасибо за помощь!',
      lastTime: 'Вчера',
      userId: 3,
    },
  ],

  messages: {
    /* Канал — только сообщения преподавателей (userId: 6) */
    1: [
      { id: 101, userId: 6, text: 'Уважаемые студенты! Расписание на следующую неделю опубликовано на портале ОАТК.', time: '10:30', reactions: [{ emoji: '👍', count: 18 }] },
      { id: 102, userId: 6, text: '15 сентября — день открытых дверей для абитуриентов. Приглашаем!', time: '09:00', reactions: [{ emoji: '👍', count: 12 }] },
    ],
    2: [
      { id: 201, userId: 2, text: 'Кто сделал лабу по HTML?', time: '11:42', reactions: [] },
      { id: 202, userId: 1, text: 'Я почти доделал, могу помочь с вёрсткой', time: '11:45', reactions: [{ emoji: '🔥', count: 2 }] },
      { id: 203, userId: 2, text: 'Дедлайн — пятница до 23:59', time: '11:50', reactions: [{ emoji: '😱', count: 3 }] },
    ],
    3: [
      { id: 301, userId: 6, text: 'Материалы к занятию по программированию выложены в личном кабинете.', time: '09:15', reactions: [{ emoji: '👍', count: 8 }] },
      { id: 302, userId: 1, text: 'Спасибо!', time: '09:20', reactions: [] },
    ],
    5: [
      { id: 501, userId: 5, text: 'Кто смотрел матч вчера?', time: '12:01', reactions: [{ emoji: '👀', count: 5 }] },
      { id: 502, userId: 4, text: 'Ещё нет, жду выходных', time: '12:03', reactions: [{ emoji: '😂', count: 2 }] },
    ],
    6: [
      { id: 601, userId: 2, text: 'Привет, Яша! Скинешь домашку по CSS?', time: '11:50', reactions: [] },
      { id: 602, userId: 1, text: 'Конечно, сейчас отправлю', time: '11:52', reactions: [{ emoji: '👍', count: 1 }] },
    ],
  },

  clubs: [
    {
      id: 1,
      name: 'IT-клуб ОАТК',
      emoji: '💻',
      description: 'Программирование, веб-разработка и подготовка к олимпиадам.',
      members: 28,
      category: 'IT',
      joined: true,
      admin: 'Ольга Сидорова',
    },
    {
      id: 2,
      name: 'Автоклуб',
      emoji: '🚗',
      description: 'Ремонт, диагностика автомобилей, участие в соревнованиях WorldSkills.',
      members: 34,
      category: 'Техника',
      joined: false,
      admin: 'Дмитрий Волков',
    },
    {
      id: 3,
      name: 'Киберспорт',
      emoji: '🎮',
      description: 'Турниры по CS2, Dota 2 и другим дисциплинам среди студентов колледжа.',
      members: 45,
      category: 'Досуг',
      joined: true,
      admin: 'Яша Кузнецов',
    },
    {
      id: 4,
      name: 'Настольные игры',
      emoji: '🎲',
      description: 'Мафия, Монополия и другие игры каждую пятницу в актовом зале.',
      members: 38,
      category: 'Досуг',
      joined: false,
      admin: 'Мария Козлова',
    },
    {
      id: 5,
      name: 'Клуб дизайна',
      emoji: '⭐',
      description: 'Создаем фирменные стили, плакаты и цифровые иллюстрации.',
      members: 41,
      category: 'Дизайн',
      joined: false,
      admin: 'Мария Козлова',
    },
    {
      id: 6,
      name: 'Литературный клуб',
      emoji: '📖',
      description: 'Читаем книги, обсуждаем авторов и литературные жанры.',
      members: 26,
      category: 'Книги',
      joined: false,
      admin: 'Мария Козлова',
    },
    {
      id: 7,
      name: 'Клуб волонтеров',
      emoji: '❤️',
      description: 'Помогаем городу, проводим акции и волонтерские выезды.',
      members: 30,
      category: 'Добро',
      joined: false,
      admin: 'Мария Козлова',
    },
    {
      id: 8,
      name: 'Клуб робототехники',
      emoji: '🤖',
      description: 'Собираем роботов, изучаем электронику и микроконтроллеры.',
      members: 32,
      category: 'IT',
      joined: false,
      admin: 'Мария Козлова',
    },
    {
      id: 9,
      name: 'Фотоклуб',
      emoji: '📸',
      description: 'Учимся снимать, обрабатывать фотографии и создавать фотопроекты.',
      members: 24,
      category: 'Фото',
      joined: false,
      admin: 'Мария Козлова',
    },
    {
      id: 10,
      name: 'Кулинарный клуб',
      emoji: '🍭',
      description: 'Готовим блюда, проводим мастер-классы и обмениваемся рецептами.',
      members: 29,
      category: 'Еда',
      joined: true,
      admin: 'Мария Козлова',
    },
    {
      id: 11,
      name: 'Танцевальный клуб',
      emoji: '🎵',
      description: 'Изучаем хореографию и готовим номера к выступлениям.',
      members: 36,
      category: 'Танцы',
      joined: false,
      admin: 'Мария Козлова',
    },
    {
      id: 12,
      name: 'Туристический клуб',
      emoji: '🌍',
      description: 'Изучаем хореографию и готовим номера к выступлениям.',
      members: 27,
      category: 'Туризм',
      joined: false,
      admin: 'Мария Козлова',
    },
  ],

  adminStats: {
    totalUsers: 980,
    onlineNow: 214,
    activeChats: 67,
    pendingReports: 2,
    announcements: 8,
  },
};
