/**
 * Mock-данные — заменяются ответами API при подключении БД
 * Омский автотранспортный колледж (ОАТК)
 */

const MOCK_DATA = {
  /** Личные коды доступа — в БД: таблица access_codes */
  accessCodes: {
    '123-123-123': 1,       // Яша Кузнецов (студент)
    '456-456-456': 6,       // Ольга Сидорова (преподаватель)
  },

  groups: ['исп341', 'исп342', 'исп343', 'ат231', 'ат232', 'э1031', 'э1032', 'тм241', 'др351'],
  directions: [
    'Информационные системы и программирование',
    'Автомобили и автомобильное хозяйство',
    'Экономика и бухгалтерский учёт',
    'Технология транспортных процессов',
    'Дорожное строительство и эксплуатация автомобильных дорог',
  ],

  users: [
    {
      id: 1,
      name: 'Яша Кузнецов',
      email: 'yasha.kuznetsov@oatk.ru',
      avatar: 'images/YASHA_KYZHECOV.avif',
      group: 'ИСП361',
      direction: 'Информационные системы и программирование',
      course: 1,
      interests: ['Python', 'Веб-разработка', 'Java'],
      online: true,
      role: 'student',
      bio: 'Первый курс ИСиП. Пишу на Python, Java, верстаю лендинги и иногда помогаю одногруппникам с лабами.',
    },
    {
      id: 2,
      name: 'Игорь Ефремов',
      email: 'wraphWFXbetter@oatk.ru',
      avatar: 'images/IgorAvatar.jpg',
      group: 'ИСП341',
      direction: 'Информационные системы и программирование',
      course: 3,
      interests: ['Дизайн', 'Кодинг', 'Автомеханика'],
      online: true,
      role: 'student',
      bio: 'Учусь на ИСиП, третий курс. Занимаюсь дизайном, кодингом и кручу гаечки в гараже.',
    },
    {
      id: 3,
      name: 'Матвей Беляев',
      email: 'imavano@oatk.ru',
      avatar: 'images/MatthewAvatar.png',
      group: 'ИСП341',
      direction: 'Информационные системы и программирование',
      course: 3,
      interests: ['Пастинг', '1С', 'Майнкрафт'],
      online: true,
      role: 'student',
      bio: 'ИСиП, третий курс. Люблю быстрый прототип в коде и классические жигули — в гараже ВАЗ 2107. Также люблю пастинг и майнкрафт.',
    },
    {
      id: 4,
      name: 'Кирилл Воркисов',
      email: 'vorkis@oatk.ru',
      avatar: 'images/VorkisAvatar.jpg',
      group: 'АТ231',
      direction: 'Автомобили и автомобильное хозяйство',
      course: 2,
      interests: ['Моторы', 'Ремонт', 'Футбол'],
      online: false,
      role: 'student',
      bio: 'Учусь на АТ, второй курс. Разбираюсь в двигателях и ремонте, после пар часто в мастерской.',
    },
    {
      id: 5,
      name: 'Антон Хехорович',
      email: 'hehora@oatk.ru',
      avatar: 'images/AntonAvatar.png',
      group: 'ИСП342',
      direction: 'Информационные системы и программирование.',
      course: 3,
      interests: ['Кошки', 'Боты', 'IRC'],
      online: false,
      role: 'student',
      bio: 'Третий курс ИСП342. Сижу в IRC, пишу ботов и иногда пропадаю из чатов на неделю.',
    },
    {
      id: 6,
      name: 'Артем Досиксов',
      email: 'dsx1337@oatk.ru',
      avatar: 'images/ArtemAvatar.jpg',
      group: '—',
      direction: 'Главный по приютам для кошечек',
      course: 0,
      interests: ['Кошки', 'Приюты', 'Тесты'],
      online: false,
      role: 'teacher',
      bio: 'Преподаватель. Веду практику и тестирование, в свободное время помогаю приютам для животных.',
    },
    {
      id: 7,
      name: 'Ольга Сидорова',
      email: 'OlgaSidorova@oatk.ru',
      avatar: 'images/AnyaPrepor.jpg',
      group: '',
      direction: 'Информационные системы и программирование',
      course: 3,
      interests: [''],
      online: false,
      role: 'teacher',
      bio: 'Преподаватель ИСиП. Мобильная разработка: Android и iOS, курсовые и учебные проекты.',
    },
    {
      id: 8,
      name: 'Александр Потапов',
      email: 'AlexanderPotapov@oatk.ru',
      avatar: 'images/AlexanderPotapov.jpg',
      group: 'АТ231',
      direction: 'Автомобили и автомобильное хозяйство',
      course: 2,
      interests: ['Авто', 'Шины', 'Дороги'],
      online: false,
      role: 'student',
      bio: 'АТ231, второй курс. Автомобили, покрышки и дорога — после колледжа хочу в сервис.',
    },
    {
      id: 9,
      name: 'Полина Калашникова',
      email: 'PolinaKalashnikova@oatk.ru',
      avatar: 'images/PolinaAvatar.jpg',
      group: 'ИСП341',
      direction: 'Информационные системы и программирование',
      course: 3,
      interests: ['iOS', 'Android', 'Код'],
      online: false,
      role: 'student',
      bio: 'ИСиП, третий курс. Собираю учебные приложения под iOS и Android.',
    },
    {
      id: 10,
      name: 'Денис Голубев',
      email: 'DenisGolubev@oatk.ru',
      avatar: 'images/DenisAvatar.jpg',
      group: 'Э1031',
      direction: 'Экономика и бухгалтерский учёт',
      course: 1,
      interests: ['Экономика', 'Учёт', 'Excel'],
      online: false,
      role: 'student',
      bio: 'Э1031, первый курс. Экономика и бухучёт, веду конспекты и считаю задачи к парам.',
    },
    {
      id: 11,
      name: 'Алексей Федоров',
      email: 'AlexeyFedorov@oatk.ru',
      avatar: 'images/AlexeyAvatar.jpg',
      group: 'ТМ241',
      direction: 'Технология транспортных процессов',
      course: 2,
      interests: ['Логистика', 'Спорт', 'Авто'],
      online: false,
      role: 'student',
      bio: 'ТМ241, второй курс. Логистика и транспорт, после пар — спортзал.',
    },
    {
      id: 12,
      name: 'Дмитрий Березин',
      email: 'DmitriyBerezin@oatk.ru',
      avatar: 'images/DmitriyAvatar.jpg',
      group: 'ДР351',
      direction: 'Дорожное строительство и эксплуатация автомобильных дорог',
      course: 3,
      interests: ['Дороги', 'Сметы', 'Спорт'],
      online: false,
      role: 'student',
      bio: 'ДР351, третий курс. Дорожное строительство, сметы и практика на объектах.',
    },
    {
      id: 13,
      name: 'Мария Козлова',
      email: 'MariaKozlova@oatk.ru',
      avatar: 'images/MariaAvatar.jpg',
      group: 'ИСП343',
      direction: 'Информационные системы и программирование',
      course: 3,
      interests: ['Код', 'UI', 'Спорт'],
      online: true,
      role: 'student',
      bio: 'ИСиП, третий курс. Верстка, интерфейсы и оформление учебных проектов.',
    },
    {
      id: 14,
      name: 'Евгений Козлов',
      email: 'EvgeniyKozlov@oatk.ru',
      avatar: 'images/EvgeniyAvatar.jpg',
      group: 'Э1032',
      direction: 'Экономика и бухгалтерский учёт',
      course: 1,
      interests: ['Учёт', 'Excel', '1С'],
      online: false,
      role: 'student',
      bio: 'Э1032, первый курс. Бухучёт и отчётность, хочу в дальнейшем работать в бухгалтерии.',
    },
    {
      id: 15,
      name: 'Дмитрий Сафронов',
      email: 'DmitriySafronov@oatk.ru',
      avatar: 'images/DmitriySafronov.jpg',
      group: 'ТМ241',
      direction: 'Технология транспортных процессов',
      course: 2,
      interests: ['Рейсы', 'Логистика', 'Спорт'],
      online: false,
      role: 'student',
      bio: 'ТМ241, второй курс. Организация перевозок и расписание маршрутов.',
    },
    {
      id: 16,
      name: 'Елена Павлова',
      email: 'ElenaPavlova@oatk.ru',
      avatar: 'images/ElenaAvatar.jpg',
      group: 'ИСП341',
      direction: 'Информационные системы и программирование',
      course: 3,
      interests: ['Код', 'Figma', 'Спорт'],
      online: false,
      role: 'student',
      bio: 'Третий курс ИСП341. Дизайн интерфейсов и вёрстка, иногда помогаю с макетами для группы.',
    },
    {
      id: 17,
      name: 'Ирина Иванова',
      email: 'IrinaIvanova@oatk.ru',
      avatar: 'images/IrinaAvatar.jpg',
      group: 'ИСП342',
      direction: 'Информационные системы и программирование',
      course: 3,
      interests: ['Код', 'Дизайн', 'Спорт'],
      online: true,
      role: 'student',
      bio: 'ИСиП, третий курс. Люблю сочетать учёбу со спортом и оформлением презентаций.',
    },
    {
      id: 18,
      name: 'Сергей Петров',
      email: 'SergeyPetrov@oatk.ru',
      avatar: 'images/SergeyAvatar.jpg',
      group: 'АТ231',
      direction: 'Автомобили и автомобильное хозяйство',
      course: 2,
      interests: ['Авто', 'Шины', 'Сервис'],
      online: false,
      role: 'student',
      bio: 'Второй курс АТ. Диагностика, шиномонтаж и устройство автомобиля.',
    },
    {
      id: 19,
      name: 'Ольга Сидорова',
      email: 'OlgaSidorova@oatk.ru',
      avatar: 'images/OlgaAvatar.jpg',
      group: 'ИСП343',
      direction: 'Информационные системы и программирование',
      course: 3,
      interests: ['SQL', 'Код', 'Диплом'],
      online: false,
      role: 'student',
      bio: 'ИСП343, третий курс. Базы данных и курсовые, готовлюсь к диплому.',
    },
    {
      id: 20,
      name: 'Иван Иванов',
      email: 'IvanIvanov@oatk.ru',
      avatar: 'images/IvanAvatar.jpg',
      group: 'Э1031',
      direction: 'Экономика и бухгалтерский учёт',
      course: 1,
      interests: ['Учёт', '1С', 'Excel'],
      online: true,
      role: 'student',
      bio: 'Первый курс экономики. Учу проводки и пока разбираюсь в 1С.',
    },
  ],

  chatTypes: {
    channel: { label: 'Канал', readonly: true },
    group: { label: 'Группа', readonly: false },
    direction: { label: 'Направление', readonly: false },
    course: { label: 'Курс', readonly: false },
    flood: { label: 'Флудилка', readonly: false },
    dm: { label: 'ЛС', readonly: false },
  },

  chats: [
    {
      id: 1,
      name: 'Объявления ОАТК',
      type: 'channel',
      avatar: null,
      icon: '📢',
      members: 980,
      description: 'Официальные объявления колледжа. Писать могут только преподаватели и администрация.',
      unread: 2,
      lastMessage: 'Расписание занятий на следующую неделю опубликовано',
      lastTime: '9:00',
    },
    {
      id: 2,
      name: 'исп341',
      type: 'group',
      avatar: null,
      icon: '👥',
      members: 25,
      description: 'Чат группы исп341. Пары, дедлайны, совместные проекты.',
      unread: 3,
      lastMessage: 'Матвей: Дедлайн на пятницу до 23:59. Я не успеваю, помоги пж!!!',
      lastTime: '11:50',
    },
    {
      id: 3,
      name: 'ИСиП — направление',
      type: 'direction',
      avatar: null,
      icon: '🎓',
      members: 124,
      description: 'Общий чат направления «Информационные системы и программирование».',
      unread: 0,
      lastMessage: 'Вы: Спасибо!',
      lastTime: '09:20',
    },
    {
      id: 4,
      name: '1 курс',
      type: 'course',
      avatar: null,
      icon: '📚',
      members: 280,
      description: 'Чат всех студентов 1 курса ОАТК.',
      unread: 0,
      lastMessage: 'Может тогда в доту поиграем?',
      lastTime: '11:52',
    },
    {
      id: 5,
      name: 'Флудилка ОАТК',
      type: 'flood',
      avatar: null,
      icon: '💬',
      members: 650,
      description: 'Свободное общение на любые темы.',
      unread: 2,
      lastMessage: 'Кирилл: Ещё нет, жду выходных',
      lastTime: '12:03',
    },
    {
      id: 6,
      name: 'Игорь Ефремов',
      type: 'dm',
      avatar: 'images/IgorAvatar.jpg',
      icon: null,
      members: 2,
      description: 'Личная переписка',
      unread: 1,
      lastMessage: 'Привет, как там Матвейка? Сделал лабу по HTML? Мб помогу вам щяс.',
      lastTime: '12:00',
      userId: 2,
    },
    {
      id: 7,
      name: 'Матвей Беляев',
      type: 'dm',
      avatar: 'images/MatthewAvatar.png',
      icon: null,
      members: 2,
      description: 'Личная переписка',
      unread: 1,
      lastMessage: 'Ну лан,я уже сам нашел решение',
      lastTime: '11:55',
      userId: 3,
    },
  ],

  messages: {
    /* Канал — только сообщения преподавателей (userId: 6) */
    1: [
      { id: 101, userId: 7, text: 'Уважаемые студенты! Расписание на следующую неделю опубликовано на портале ОАТК.', time: '10:30', reactions: [{ emoji: '👍', count: 18 }] },
      { id: 102, userId: 7, text: '15 сентября — день открытых дверей для абитуриентов. Приглашаем!', time: '09:00', reactions: [{ emoji: '👍', count: 12 }] },
    ],
    2: [
      { id: 201, userId: 2, text: 'Кто сделал лабу по HTML?', time: '11:42', reactions: [] },
      { id: 202, userId: 1, text: 'Я почти доделал, могу помочь с вёрсткой', time: '11:45', reactions: [{ emoji: '🔥', count: 2 }] },
      { id: 203, userId: 3, text: 'Дедлайн на пятницу до 23:59. Я не успеваю, помоги пж!!!', time: '11:50', reactions: [{ emoji: '😱', count: 3 }] },
    ],
    3: [
      { id: 301, userId: 7, text: 'Материалы к занятию по программированию выложены в личном кабинете.', time: '09:15', reactions: [{ emoji: '👍', count: 8 }] },
      { id: 302, userId: 1, text: 'Спасибо!', time: '09:20', reactions: [] },
    ],
    4: [
      { id: 401, userId: 4, text: 'Всем привет! У кого какие планы на выходные?', time: '11:42', reactions: [] },
      { id: 402, userId: 1, text: 'Я свободен', time: '11:50', reactions: [{ emoji: '🔥', count: 2 }] },
      { id: 403, userId: 3, text: 'Я думал поиграть в комп', time: '11:51', reactions: [{ emoji: '🔥', count: 1 }] },
      { id: 404, userId: 4, text: 'Может тогда в доту поиграем?', time: '11:52', reactions: [{ emoji: '👍', count: 3 }] },
    ],
    5: [
      { id: 501, userId: 5, text: 'Кто смотрел матч вчера?', time: '12:01', reactions: [{ emoji: '👀', count: 5 }] },
      { id: 502, userId: 4, text: 'Ещё нет, жду выходных', time: '12:03', reactions: [{ emoji: '😂', count: 2 }] },
    ],
    6: [
      { id: 601, userId: 2, text: 'Привет, как там Матвейка? Сделал лабу по HTML? Мб помогу вам щяс', time: '12:00', reactions: [] },
    ],
    7: [
      { id: 701, userId: 3, text: 'ПОМОГИ МНЕ ПЛЗ!!!', time: '11:50', reactions: [] },
      { id: 702, userId: 1, text: 'Кто вы, Матвей? Я не знаю вас. Не пишите сюда больше.', time: '11:52', reactions: [{ emoji: '👍', count: 1 }] },
      { id: 703, userId: 3, text: 'Ну лан,я уже сам нашел решение', time: '11:53', reactions: [{ emoji: '👍', count: 1 }] },
    ],
  },

  clubs: [
    {
      id: 1,
      name: 'IT-клуб ОАТК',
      emoji: '💻',
      description: 'Программирование, веб-разработка и подготовка к олимпиадам.',
      members: 28,
      category: 'IT',
      joined: true,
      admin: 'Ольга Сидорова',
    },
    {
      id: 2,
      name: 'Автоклуб',
      emoji: '🚗',
      description: 'Ремонт, диагностика автомобилей, участие в соревнованиях WorldSkills.',
      members: 34,
      category: 'Техника',
      joined: false,
      admin: 'Кирилл Воркисов',
    },
    {
      id: 3,
      name: 'Киберспорт',
      emoji: '🎮',
      description: 'Турниры по CS2, Dota 2 и другим дисциплинам среди студентов колледжа.',
      members: 45,
      category: 'Досуг',
      joined: true,
      admin: 'Яша Кузнецов',
    },
    {
      id: 4,
      name: 'Настольные игры',
      emoji: '🎲',
      description: 'Мафия, Монополия и другие игры каждую пятницу в актовом зале.',
      members: 38,
      category: 'Досуг',
      joined: false,
      admin: 'Мария Козлова',
    },
    {
      id: 5,
      name: 'Клуб дизайна',
      emoji: '⭐',
      description: 'Создаем фирменные стили, плакаты и цифровые иллюстрации.',
      members: 41,
      category: 'Дизайн',
      joined: false,
      admin: 'Мария Козлова',
    },
    {
      id: 6,
      name: 'Литературный клуб',
      emoji: '📖',
      description: 'Читаем книги, обсуждаем авторов и литературные жанры.',
      members: 26,
      category: 'Книги',
      joined: false,
      admin: 'Мария Козлова',
    },
    {
      id: 7,
      name: 'Клуб волонтеров',
      emoji: '❤️',
      description: 'Помогаем городу, проводим акции и волонтерские выезды.',
      members: 30,
      category: 'Добро',
      joined: false,
      admin: 'Мария Козлова',
    },
    {
      id: 8,
      name: 'Клуб робототехники',
      emoji: '🤖',
      description: 'Собираем роботов, изучаем электронику и микроконтроллеры.',
      members: 32,
      category: 'IT',
      joined: false,
      admin: 'Мария Козлова',
    },
    {
      id: 9,
      name: 'Фотоклуб',
      emoji: '📸',
      description: 'Учимся снимать, обрабатывать фотографии и создавать фотопроекты.',
      members: 24,
      category: 'Фото',
      joined: false,
      admin: 'Мария Козлова',
    },
    {
      id: 10,
      name: 'Кулинарный клуб',
      emoji: '🍭',
      description: 'Готовим блюда, проводим мастер-классы и обмениваемся рецептами.',
      members: 29,
      category: 'Еда',
      joined: true,
      admin: 'Мария Козлова',
    },
    {
      id: 11,
      name: 'Танцевальный клуб',
      emoji: '🎵',
      description: 'Изучаем хореографию и готовим номера к выступлениям.',
      members: 36,
      category: 'Танцы',
      joined: false,
      admin: 'Мария Козлова',
    },
    {
      id: 12,
      name: 'Туристический клуб',
      emoji: '🌍',
      description: 'Изучаем хореографию и готовим номера к выступлениям.',
      members: 27,
      category: 'Туризм',
      joined: false,
      admin: 'Мария Козлова',
    },
  ],

  adminStats: {
    totalUsers: 980,
    onlineNow: 214,
    activeChats: 67,
    pendingReports: 2,
    announcements: 8,
  },
};
